### ISSUE TITLE
Update of items leads to invalid relations

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#142]
In GitLab by @KlausIllmayer on Jan 13, 2022, 13:17

We ran into a situation where we had on stage relations between items, where one of the items was not valid anymore due to an re-ingest. Thus we could see the relation on side of the active item but it lead to a 404 as the referenced item was not available. So it seems to us that somewhere on backend a check on relations is missing, that would cover this situation and delete the relation. As we were also not able to delete the relations with the API call `DELETE /api/items-relations/{subjectId}/{objectId}` as it gaves us - correctly, due to the link to a not valid item - a 404 back, the only solution was to manually delete the relations in the database (hoping that there is no side effect after simple deleting these wrong relations in the items_related_items-table.

Trying to explain how it comes to this and asking @vronk for his perspective: Sotiris did an update of the steps of the SSK (so it could be that this is an issue only relevant for the `steps`). These steps are related to other items from the Zotero list. Whereas the items from the Zotero list weren't changed, the steps did get a new version. But it seems that the relation between the steps and the items weren't updated on the steps side, thus refering to the previous and now invalid version of an item.

I'm not sure if this is enough information, so that you have identify the incident in the backend code. If you need some more background, please ask Sotiris and me.

**Comment by KlausIllmayer** [comment]
As Laure already pointed out, the way she discovered how the bug expresses is already fixed. For the initial comment I'm not able to repeat the issue again. Therefore closing the issue but watching for the continuous ingestion if they do not run in the same problem.
