### ISSUE TITLE
draft-items do also show steps

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#161]
In GitLab by @KlausIllmayer on Mar 2, 2022, 16:23

When calling /api/draft-items it will return also the steps of a draft workflow as separate items:

![grafik](https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/uploads/1d6008f516f433935fa33525fa77e9f5/grafik.png)

But when clicking on the item we run into a 404 as we can't directly call the step. This is not very satisfying for users.
I see two solutions: backend does not deliver steps when calling /api/draft-items or frontend hides such steps or changes the url to the workflow.

Which option do you prefer or is there no need to change this @tparkola @stefanprobst ?

Including @egray523 and @laureD19 for further opinions

**Comment by KlausIllmayer** [comment]
This is solved from perspective of backend:

`GET /api/draft-items` does not deliver anymore steps
`GET /api/workflows/{persistentId}?draft=true` does deliver the steps

Therefore it looks like frontend has not implemented it and there is already an issue dealing with it: https://github.com/SSHOC/sshoc-marketplace-frontend/issues/129
