### ISSUE TITLE
Removing externalIds are not working

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#170]
In GitLab by @KlausIllmayer on Oct 25, 2022, 11:59

As reported in https://gitlab.gwdg.de/sshoc/sshoc-marketplace-frontend/-/issues/121 we recently discovered, that it is currently not possible to remove externalIds from items. We can eliminate that there is a problem with frontend, therefore the bug must be somewhere in the backend code.

I tried it out with calls only to the API and the problem can be reproduced:

1. Create an item with an externalId
<details><summary>POST /api/tools-services</summary>
<pre>
{
  "label": "test external id delete",
  "description": "like to delete external id",
  "externalIds": [
    {
      "identifierService": {
        "code": "GitHub"
      },
      "identifier": "home/common"
    }
  ]
}
</pre>
</details>

2. Update the item without the externalId
<details><summary>PUT /api/tools-services/{persistentId}</summary>
<pre>
{
  "label": "test external id delete",
  "description": "like to delete external id",
  "externalIds": []
}
</pre>
</details>
You can already see in the returned body that the externalID "GitHub: home/common" still exists.

3. Get the item to see, if the externalId exists
<details><summary>GET /api/tools-services/{persistentId}</summary>
no body necessary
</details>
You can see in the returned body that the externalID "GitHub: home/common" still exists and is not deleted, as expected.

@tparkola Can you have a look, why deleting externalIds does not work? Is it a bug or is it the wrong way, how I did it?

Notify @laureD19

**Comment by KlausIllmayer** [comment]
tested it after merging https://github.com/SSHOC/sshoc-marketplace-backend/pull/365 - can confirm that it works on stage
