### ISSUE TITLE
Implement sorting of actors and concepts

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#171]
In GitLab by @KlausIllmayer on Oct 27, 2022, 13:13

Based on this discussion in frontend: https://gitlab.gwdg.de/sshoc/sshoc-marketplace-frontend/-/issues/88#note_671346 - it would be helpful to have a sorting parameter not only for items (here it is already implemented `/api/item-search`) but also for actors (`/api/actor-search`) and concepts (`/api/concept-search`)

**Comment by stefanprobst** [comment]
@KlausIllmayer do you want to review+merge this?
