### ISSUE TITLE
bug - saving as draft or submitting items

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#172]
In GitLab by @laureD19 on Nov 16, 2022, 19:44

while creating an item from scratch, and adding specific URLs in the accessibleAt field, it creates a bug and prevent the item to be "save as draft" or "submitted". 

error message received on the edit form: "Last submission failed: Source item id is required because source was matched with 'CLARIN Resource Families' by Accessible at Url." >>> with the following URL used in accessibleAt: 

![image](https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/uploads/9c0445911a3f28e9b75d4d7d5ce2584c/image.png)

error message received on the edit form: "Last submission failed: Source item id is required because source was matched with 'The Programming Historian' by Accessible at Url." For indeed a PH url in accessibleAt:
![image](https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/uploads/310d54d0fee8221cdd6c7e27381929b5/image.png)

this bug has been encountered today during the workshop on the production instance by several users. I've reproduced on stage for these last examples. 

bug connected to: https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/-/issues/169 

notify also @KlausIllmayer @stefanprobst @vronk

**Comment by laureD19** [comment]
solved together with #169
