### ISSUE TITLE
Setup auto-deploy from github to ACDH-CH servers

### ISSUE THREAD

**Issue by vronk** [SSHOC/sshoc-marketplace-backend#371]
After migration from gitlab-gwdg to github, we need to set up the deployment workflow a new (as github actions).

Could we use this opportunity also to move to acdh-ch-cluster2

**Comment by KlausIllmayer** [comment]
We created a first version on our Kubernetes cluster manually and it works. Next step is to have an automated version using Helm charts. We then try it out with moving the develop version including the database to the ACDH-CH Kubernetes cluster. If this works, we will repeat it with stage and finally with develop. This will then mean that the auto-deploy is in place and we can approve the pull requests.

**Comment by KlausIllmayer** [comment]
Helm charts are [in place](https://github.com/SSHOC/sshoc-marketplace-backend/tree/develop/chart), thanks to @simar0at. We are now able to deploy instances of SSHOMP on our K8s cluster. There is already a test instance to replace develop and stage. We test it this week and if everything works fine, the production instance will also be replaced and we can switch fully to K8s. Afterwards the pull requests will be accepted.

**Comment by KlausIllmayer** [comment]
We have now tested it and already merged some pull request. Works all as expected, there is only one minor problem with randomly occuring database locks, see #383 - maybe we find a fix for this.

I will also once again try to deploy on all instances of the MP with the help of the workflow. If this works, this issue will be closed.

**Comment by KlausIllmayer** [comment]
Deploy worked perfectly - closing the issue.
