### ISSUE TITLE
Introduce a force parameter to delete actors

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#388]
We can delete actors that have never been applied to an item and when merging actors, the ones that are merged will be also deleted. What we miss is the option to delete actors that are currently not applied to any item but once have been applied to an item. We currently don't have an option to delete such actors.

We once discussed this (see #143) but the issue was closed (I guess we thought that it is not necessary). In the meantime we came to the conclusion, that for clean-up reasons it could be indeed useful, to have a parameter "force" (as we have it in some other API calls, especially for vocabulary concepts) that allows to delete such actors. We manipulate the history of items with such an option, but it should be really limited only to actors, that do not have any active relation to an item.

The additional force parameter should cover this:
* parameter "force" for `DELETE /api/actors/{id}` of type boolean: true/false
* only role >= moderator can use it (or should we even limit it only to administrators?)
* the actor to delete is not applied to any active item

What do you think @tparkola @laureD19 ?

**Comment by laureD19** [comment]
Taking into account "active"/"inactive" versions of items. Deletion of actors should only be possible for "inactive"versions of items.

**Comment by tparkola** [comment]
The parameter is introduced. It can be used only by administrators plus the actor (that is to be deleted) cannot be linked to an active version of an item. The result is that the actor disappears from the history of all versions of items.

**Comment by KlausIllmayer** [comment]
@tparkola One question: you write that "adminstrators plus the actor" can delete an actor - I'm not sure, how this could work, as we separate users from actors in the database. I think a user can only act as informationContributor but not as an actor. Looking into the code it seems to me that only administrators are allowed to do this, right?

**Comment by KlausIllmayer** [comment]
An open issue here is that when deleting an actor who is still a contributor of an active item you get a not very nice error message when using `force=false` :
```
{
  "timestamp": "2023-08-18 14:52:21",
  "status": 500,
  "error": "could not execute statement; SQL [n/a]; constraint [item_contributor_actor_id_fk]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
```
You can try it out on stage with `DELETE /api/actors/1763?force=false`.
If you use `force=true` the error message is way more nicer:
```
{
  "timestamp": "2023-08-18 15:01:29",
  "status": 400,
  "error": "Cannot delete actors that are contributors of active items!"
}
```
@tparkola Can we also give this error message when using `force=false` (which is also the default when not explicit adding `force`)? And do you prefer to have this in a dedicated issue or can you re-use this issue?

**Comment by KlausIllmayer** [comment]
There is also the special case where an actor is not applied to any item but it is the affiliation of other actors. It would be great to have a nice error message for such cases, currently it returns:
```
{
  "timestamp": "2023-08-18 15:45:05",
  "status": 500,
  "error": "could not execute statement; SQL [n/a]; constraint [actors_affiliations_affiliation_id_fk]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
```
On stage you can try it out with `DELETE /api/actors/990?force=true`.
@tparkola Can we have instead a 400 status with error "Cannot delete actors that are affiliations of other actors"?

**Comment by tparkola** [comment]
> There is also the special case where an actor is not applied to any item but it is the affiliation of other actors. It would be great to have a nice error message for such cases, currently it returns:
> 
> ```
> {
>   "timestamp": "2023-08-18 15:45:05",
>   "status": 500,
>   "error": "could not execute statement; SQL [n/a]; constraint [actors_affiliations_affiliation_id_fk]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
> }
> ```
> 
> On stage you can try it out with `DELETE /api/actors/990?force=true`. @tparkola Can we have instead a 400 status with error "Cannot delete actors that are affiliations of other actors"?

I will fix it here, no problem.

**Comment by tparkola** [comment]
> There is also the special case where an actor is not applied to any item but it is the affiliation of other actors. It would be great to have a nice error message for such cases, currently it returns:
> 
> ```
> {
>   "timestamp": "2023-08-18 15:45:05",
>   "status": 500,
>   "error": "could not execute statement; SQL [n/a]; constraint [actors_affiliations_affiliation_id_fk]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
> }
> ```
> 
> On stage you can try it out with `DELETE /api/actors/990?force=true`. @tparkola Can we have instead a 400 status with error "Cannot delete actors that are affiliations of other actors"?

Yes, will do so.

**Comment by KlausIllmayer** [comment]
Unfortunately, by introducing the conditional "Cannot delete actors that are contributors of items!" - [in code review](https://github.com/SSHOC/sshoc-marketplace-backend/pull/412/files#diff-26b167ac76ae083c470a262f1fd086b759d4831b685459fa3939d4a39d8d0d39R129) - it is not possible anymore to delete once applied actors as described in https://github.com/SSHOC/sshoc-marketplace-backend/issues/388#issuecomment-1684126204. the reason seems to me that in the corresponding [query](https://github.com/SSHOC/sshoc-marketplace-backend/pull/412/files#diff-ee3311be2896e1b77e59ce56e036073b34ed8c47ac5f9a7ecf903ee48fc241f5R88) you don't limit to active items thus it will not allow you to delete an actor (I think this looks like a working example: [code](https://github.com/SSHOC/sshoc-marketplace-backend/blob/c3a9ba3a5605823ce454114d97b74b9b41318005/src/main/java/eu/sshopencloud/marketplace/repositories/items/ItemRepository.java))

**Comment by KlausIllmayer** [comment]
yes, you are right - sorry about that, everything works as expected
