### ISSUE TITLE
Extend search endpoint covering more fields

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#391]
Recently, we got suggestions to extend the search options for the marketplace. In EOSCFuture there was the question, if it would be able to search for DOIs. Another suggestion was to be able to use the search bar to find items connected to a specific actor (look for the name of the actor in the search bar).

First of all, we would need to collect the fields, that would make sense when extending the search endpoint. Then it must be implemented in the backend so that it can be taken over by frontend. If backend implements this, frontend must not care about it, but to make more clearer why a search result shows up, e.g. when looking for the name of an actor, we would need some better indicators in the frontend.

@laureD19 What do you think, could this be something that we discuss in the Editorial Board to come up with a list of fields that would be useful (and feasible) for extension of the search endpoint?

**Comment by laureD19** [comment]
actors search is definitely one to prioritise (it is on the wish list for a while now, based on specific use of the MP within DARIAH community, but also requirements collected during the last workshops). So I would not wait for this one, to be sure about others. 

The topic is added to next EB meeting though, so we can collect other suggestions from the colleagues.

**Comment by laureD19** [comment]
extend the search with actors. No facets in search results

**Comment by KlausIllmayer** [comment]
Commiting the pull request will re-run the Solr index. We need to be aware about this when pushing to the production code.

**Comment by KlausIllmayer** [comment]
Search for contributors is now part of the q-parameter of `api/item-search` (`d.contributor` was not touched, be aware that d.contributor uses no wildcards by default, so either you look for the full name of a contributor or use a wildcard like `*`)

**Comment by KlausIllmayer** [comment]
Works also on production

**Comment by laureD19** [comment]
- other fields to cover? i.e. DOIs > new issue to open if other fields
