### ISSUE TITLE
Mixed up results for concept list

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#397]
Cesare found out that when processing the full concept list of the rather big vocabulary [sshoc-keyword](https://marketplace-api.sshopencloud.eu/api/vocabularies/sshoc-keyword) there are some concepts missing and some concepts are duplicated (the same concepts, identified by the code). I'm still trying to find a repeatable example, but chances are high, that it could share the same problems as identified in #373. Especially, as it seems that it is connected to pagination. @tparkola Can you have a look into the `GET /api/vocabularies/{code}` if there is the same problem with creating pages as we saw for `GET /api/actors`?

**Comment by tparkola** [comment]
In theory it should not cause similar problems. In case of vocabularies the order is by "ord" value from the database, so it should be fine. I went through the whole vocabulary (on production site that you mentioned) with perpage=100 and found only one page with `sitemap` code. Can you provide me links to two separate pages of results that contain the same code? Or is this happening randomly in your experience?

**Comment by KlausIllmayer** [comment]
Fix works like a charm, can't now find any duplicates with the script.

**Comment by KlausIllmayer** [comment]
Follow up regarding multiple concepts having the same "ord" value: #420
