### ISSUE TITLE
OAI-PMH endpoint

### ISSUE THREAD

**Issue by tparkola** [SSHOC/sshoc-marketplace-backend#408]
Implement OAI-PMH endpoint for the SSH Open Marketplace. Keep basic approach:
- only oai_dc metadata prefix is supported
- optional features are not needed for the time being, only minimum set of requirements

**Comment by KlausIllmayer** [comment]
After commiting this pull request and after successful deployment of the new code on the stage/develop instances at our servers, the index was only in parts accessable (on the front page only some items showed up and when using the auto-complete, items like "Gephi" weren't findable) and I saw in the Solr-logfiles, that a full index-rebuilt was started.

The easiest explanation would have been, that this was intended in the pull request but judging on your answer, this is not the case. Therefore I need to check, what else could have initiated this state, as it has an effect on the deployment on production as such a re-index takes some hours.

**Comment by tparkola** [comment]
Hm, I do not know the deployment details, but from what I see the reindex of items, autocomplete, concepts and actors is done every time the app is starting. See https://github.com/SSHOC/sshoc-marketplace-backend/blob/develop/src/main/java/eu/sshopencloud/marketplace/conf/startup/MarketplaceStartupRunner.java. However, I may miss something. Let me know if there are other circumstances.
