### ISSUE TITLE
Replace spring data for solr with alternative

### ISSUE THREAD

**Issue by tparkola** [SSHOC/sshoc-marketplace-backend#417]
As spring data for solr has been discontinued (https://spring.io/blog/2020/04/07/spring-data-for-apache-solr-discontinued) we need to remove this dependency and replace it with alternative (e.g. solrj).

**Comment by laureD19** [comment]
cf. [11.12.23 dev meeting](https://docs.google.com/document/d/1rG6tqapCyfW9kDHoVKk7rvb1CF3jJaDwH-nD_0vcLnc/edit?pli=1) - rough estimation 1PM
