### ISSUE TITLE
Allow to have titles and description in multiple languages

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#421]
There is some feedback asking for a technical clean solution to apply titles and descriptions of items in multiple languages. This is something to be discussed into more detail, if we like to deal with multilingualism. There are sure many libraries dealing with this in Java but it must be evaluated how easy you can integrate them into the marketplace. There are also questions about how to show multiple languages in frontend, if an English title is mandatory, how the search index can deal with it, etc.

First step would be to generally discuss it and see, if it is doable in the near future or if it is too much effort with the current available resources.

**Comment by laureD19** [comment]
- decision to not implement any multilingual features
