### ISSUE TITLE
Concept search pagination overflow

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#426]
When using the concept-search endpoint there is a bug with the page-parameter. If you use a number that is bigger than the maximum page count it still shows a result list (the one from the last page), try this out: https://marketplace-api.sshopencloud.eu/api/concept-search?page=80000

Expected behaviour (like it is for the other search-endpoints): no result list, look e.g. at https://marketplace-api.sshopencloud.eu/api/item-search?page=80000

**Comment by tparkola** [comment]
I checked two links you provided and both have empty result lists. Maybe I misunderstood something, please verify again and confirm you still have described issue/problem. Or rephrase maybe if some issues are still there.

**Comment by vronk** [comment]
This seems to work as expected
