### ISSUE TITLE
Vocabulary export misses labels

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#427]
When creating an export of a vocabulary, e.g. `GET /api/vocabularies/sshoc-keyword/export` the resulting ttl-file does not contain all available values. Especially it misses for some concepts the label, expressed in skos:label.

To test it:

1. Call https://marketplace-api.sshopencloud.eu/api/vocabularies/sshoc-keyword/export and save the sshoc-keyword.ttl-file locally
2. Open the sshoc-keyword.ttl-file and look for the concept 1960s: `<https://vocabs.sshopencloud.eu/vocabularies/sshomp-keyword/1960s> a skos:Concept;` - the expressed concept does not have a label, strangely it has a skos:notation.
3. Look for the concept in the marketplace: https://marketplace-api.sshopencloud.eu/api/vocabularies/sshoc-keyword/concepts/1960s - there you see a label
4. I would expect to see in the sshoc-keyword.ttl-file the label as skos:prefLabel like it is the case for other concepts, e.g. `<https://vocabs.sshopencloud.eu/vocabularies/sshomp-keyword/19th-century> a skos:Concept;`

This is maybe connected to #425 at least there the reason for the necessity of having skos:prefLabel is explained.

Informing @laureD19 @vronk @cesareconcordia about this issue.
 @tparkola could you look into the code to find an explanation for this strange behaviour?

**Comment by cesareconcordia** [comment]
There are also Concepts that has neither `skos:prefLabel` nor `skos:notation`, for instance `20thCenturyLiterature`.  Moreover it would be better to use URIs as object for predicates `skos:topConceptOf`  and `skos:inScheme`.

**Comment by KlausIllmayer** [comment]
> Moreover it would be better to use URIs as object for predicates `skos:topConceptOf` and `skos:inScheme`.

That would be something to discuss. I recommend to not use the full URI for these predicates and use instead the namespace, as it is currently the case. There are some advantages connected to this approach. I don't think, that there is an official recommended way how to deal with it.

**Comment by KlausIllmayer** [comment]
> There are also Concepts that have neither `skos:prefLabel` nor `skos:notation`, for instance `20thCenturyLiterature`.

#425 describes this. If you don't add label or notation to the POST endpoint of creating a new vocabulary concept it will also not be added in the marketplace database (API GET endpoint) or the export file. The reason, why it is currently so different on side of the marketplace database, is that either the ingest pipelines or e imported vocabulary dump files handled this in different ways. I think on side of the creation of concepts/vocabularies we are quite okay, it is really more the export that makes problems and that we didn't define any mandatory fields next to code.

**Comment by cesareconcordia** [comment]
> > Moreover it would be better to use URIs as object for predicates `skos:topConceptOf` and `skos:inScheme`.
> 
> That would be something to discuss. I recommend to not use the full URI for these predicates and use instead the namespace, as it is currently the case. There are some advantages connected to this approach. I don't think, that there is an official recommended way how to deal with it.

agree with you, I did not explain well the point, what I meant is that currently the object in triples with predicates  topConceptOf and inScheme is formatted as a Literal, I would suggest to format it as URI.

**Comment by tparkola** [comment]
There are two fields in the concept related to label. One is simply "label" and the other one is called "labels". The first one (label) is filled in when creating concepts via update/create API (regular use of the API as I presume). The second one (labels) is filled in when import from ttl file is executed - during this import label is also filled in with a value indicated as "en" in the labels of concepts from ttl file. To clarify more - labels filed includes JSON string that has key-value pairs - the key indicates language and the value indicates label (in the language indicated by key as I presume). 

Now, the export mechanism takes only labels  (with 's' at the end) into consideration and this is the main reason why it is not in some cases in the export file. Hence, a quick fix would be to add to the export file value of a label field as an English ("en") entry. Would that be OK from your point of view? 

As a general note - this is some form of inconsistency which I would like to remove in the future, but for the time being a quick fix could be prepared (as proposed above). Proper solution could use multilingual mechanism that we discuss here: https://github.com/SSHOC/sshoc-marketplace-backend/issues/421. I think the current solution was probably created to quickly satisfy import feature from ttl files.
