### ISSUE TITLE
include `accessibleAt` in results from `/api/item-search`

### ISSUE THREAD

**Issue by stefanprobst** [SSHOC/sshoc-marketplace-backend#443]
it would be cool if results from `/api/item-search` (i.e. https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=#model-SearchItem) could include `accessibleAt` - this would make synchronizing tools-and-services with DARIAH Unified National Report (UNR) App easier. thanks!

**Comment by tparkola** [comment]
The change will require reconfiguration of solr, so I would suggest to first handle https://github.com/SSHOC/sshoc-marketplace-backend/pull/416 - integrate newer version of solr into the main branch. Then we could work further here.

**Comment by stefanprobst** [comment]
in addition to `accessibleAt`, it would also be good to include the `thumbnail` field in the `/api/item-search` response.

although we are not displaying thumbnails in the search results list on the marketplace site (we have custom icons per resource type), other services are querying the sshoc api (e.g. dariah.eu tools & services, atrium services catalogue), and they will want to have the thumbnail available.

let me know if i should open a separate issue for this.

**Comment by tparkola** [comment]
@stefanprobst - in case of thumbnail - what kind of information would you expect to get, e.g. media id (so that one can use API to download it)?

**Comment by tparkola** [comment]
OK, done, the names are accessibleAt (a list of string values) and thumbnailId (single string value).
